# production:
#   adapter: mysql2
#   encoding: utf8
#   pool: 2
#   database: <%= "'#{ ENV['MYSQLS_DATABASE'] }'" %>
#   host: <%= "'#{ ENV['MYSQLS_HOSTNAME'] }'" %>
#   port: <%= ENV["MYSQLS_PORT"] %>
#   username: <%= "'#{ ENV['MYSQLS_USERNAME'] }'" %>
#   password: <%= "'#{ ENV['MYSQLS_PASSWORD'] }'" %>

common: &common
  adapter: postgresql
  encoding: utf8
  pool: 5
  host:
  port:
  username: 
  password: 

development:
  <<: *common
  database: 

test:
  <<: *common
  database: 

production:
  <<: *common
  database: 
